# Generated by Django 4.2.4 on 2023-10-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterUser',
            new_name='RegisteredUser',
        ),
    ]
