# Generated by Django 4.2.4 on 2023-10-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_registeruser_registereduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereduser',
            old_name='phone_no',
            new_name='phone_number',
        ),
    ]
