# Generated by Django 4.2.4 on 2023-10-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_phone_no_registereduser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='experience',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=25, null=True),
        ),
    ]
